import { Dongle, Open_Sans } from "next/font/google";
import "./globals.css";

const dongle = Dongle({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-dongle",
});
const sans = Open_Sans({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dongle.variable} ${sans.variable}`}>{children}</body>
    </html>
  );
}
